### PR TITLE
Add a basic build pipeline

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I did not add a release pipeline as there are many action options there with varying results... As an example you may want to look at one of the following:
https://github.com/antoniovazquezblanco/GhidraDeviceTreeBlob/blob/main/.github/workflows/main.yml
https://github.com/antoniovazquezblanco/Cartographer/blob/ci/.github/workflows/build.yml
https://github.com/sigurasg/GhidraTek2465/blob/main/.github/workflows/ci.yml

### CODE REVIEW

**Comment by AngeloD2022** [comment]
Thanks! I'll take a look at this!

**Comment by antoniovazquezblanco** [comment]
Hi @AngeloD2022, have you had any time to look into this? :D

**Comment by fmagin** [comment]
I guess Angelo didn't get around to it yet, but I'm somewhat familiar with Ghidra CI processes, and this does certainly look better than the current state of affairs.

> I did not add a release pipeline as there are many action options there with varying results

I usually use a setup where a commit tagged with `v*.*.*` triggers a release, what other options do you see for this? I have never combined this with a matrix of Ghidra versions though, so I'm not sure how that would interact exactly.

**Comment by fmagin** [comment]
Some setup to create a GitHub release for the version of a tagged commit sounds good, and I'd appreciate that. The release should then contain the built plugins for each Ghidra version as an artifact.

It gets tricky if we actually have a breaking change between Ghidra versions, but I think in that case it would be acceptable to just change the support matrix if we can't find an implementation that supports a larger range of versions?

I don't think we need nightly builds like in the GhidraDeviceTreeBlob project, we can just create new releases often, and anyone really impatient can just build the plugin itself. The built process is fairly quick anyway, so I see little point in pre-compiling 

Is there some good way to share the support matrix, Java version and other info between multiple workflows? Because I think we should also have a workflow that attempts to build the plugin and runs some tests (if we ever have any...), on every commit. That's cheap enough and prevents basic errors slipping through. I usually did this via multiple work flow files, but then I have to define the Ghidra versions in each workflow.

**Comment by antoniovazquezblanco** [comment]
> Is there some good way to share the support matrix, Java version and other info between multiple workflows?

You can use the same file and add a second job in the same file that is only triggered on a tag presence:
```
  release:
    runs-on: ubuntu-latest
    needs: build # This is to wait for all the previous jobs to finish...
    if: contains(github.ref, 'refs/tags/v') # Only executed if a tag has been pushed...

    steps:
    # This downloads the artifacts from the build job...
    - name: Download binaries
      uses: actions/download-artifact@v4

    # Use your preferred action here...
    - name: Release stable
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "GhidraApple ${{github.ref_name}}"
        files: GhidraApple*/*.zip
```

**Comment by antoniovazquezblanco** [comment]
Maybe this is what you are looking for:
https://github.com/sigurasg/GhidraTek2465/blob/main/.github/workflows/ci.yml

:)

**Comment by AngeloD2022** [comment]
Hi Antonio,

My apologies for the delay. I suppose I figured we could integrate this when we had more features really polished and ready-for-use.

**Comment by fmagin** [comment]
I think we should merge the current suggestion now, as a basic safe guard for developing, so we at least notice if we accidentally commit code that doesn't even build correctly. (This definitely has happened to me before, when only packing a subset of local changes into a commit)

For that it would be sufficient to only built against one latest Ghidra version

**Comment by AngeloD2022** [comment]
All good with me!

**Comment by fmagin** [comment]
@antoniovazquezblanco is there a way to always build against the latest available Ghidra version without having to change it?

**Comment by AngeloD2022** [comment]
@fmagin We might need to retrieve that information from the NSA repository somehow. Or maybe Antonio could implement `ghidra-latest` as a version parameter for his action. Either way, probably not a huge deal, since Ghidra updates aren't frequent enough for it to be a PITA (in my opinion).

**Comment by antoniovazquezblanco** [comment]
> @antoniovazquezblanco is there a way to always build against the latest available Ghidra version without having to change it?

You can use the setup action and either pass the constant `'latest'` to the version field or leave it empty. It will fetch the latest availabe ghidra version.

**Comment by fmagin** [comment]
> Either way, probably not a huge deal, since Ghidra updates aren't frequent enough for it to be a PITA (in my opinion).

well, if it's one plugin, but at this point I am maintaining a handful of plugins, and changing the version in each one for each update gets annoying...


@AngeloD2022 can you activate GitHub actions so we can test this PR already before merging it?

@antoniovazquezblanco I changed the version to only use latest according to how I understood you, and I am ready to merge this now

**Comment by AngeloD2022** [comment]
@fmagin It looks as though actions are already enabled? Unless there's something I'm missing.
image

**Comment by antoniovazquezblanco** [comment]
Thank you guys!

**Comment by AngeloD2022** [comment]
Thank you!

**Pull request merged**
